export const LOGIN= "LOGIN";
export const LOGOUT= "LOGOUT";
export const USER_BY_TOKEN = "USER_BY_TOKEN";
export const EDIT_HANDLER_PROFILE="EDIT_HANDLER_PROFILE";
export const EDIT_OWNER_PROFILE="EDIT_OWNER_PROFILE";
export const EDIT_TRAINER_PROFILE="EDIT_TRAINER_PROFILE";
export const EDIT_USER_PROFILE="EDIT_USER_PROFILE";